# Copyright 2018 Cargill Incorporated
# Copyright 2023 Bitwise IO, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f validator/Dockerfile-installed-jammy -t sawtooth-validator .

FROM ubuntu:jammy

ENV VERSION=AUTO_STRICT

RUN apt-get update \
  && apt-get install -y -q \
    curl \
    git \
    libssl-dev \
    libzmq3-dev \
    pkg-config \
    protobuf-compiler \
    python3 \
    python3-pip \
    unzip

RUN pip install \
  grpcio-tools

RUN curl https://sh.rustup.rs -sSf > /usr/bin/rustup-init \
 && chmod +x /usr/bin/rustup-init \
 && rustup-init -y

ENV PATH=$PATH:/protoc3/bin:/root/.cargo/bin \
    CARGO_INCREMENTAL=0

RUN cargo install just

RUN ln -s /usr/bin/python3 /usr/bin/python

COPY . /project

RUN cd /project \
  && just clean

RUN /project/bin/protogen

RUN cd /project/validator \
  && pip install .

RUN cd /project/cli \
  && pip install .

RUN cd /project/validator \
  && cargo build \
  && cargo install --root=/usr --path . \
  && cp target/debug/libsawtooth_validator.so /usr/lib

RUN cd /project/adm \
  && cargo build \
  && cargo install --root=/usr --path .
